drivers: qca-wifi-host-cmn: Fix error cause a function declaration is deprecated
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.c:1320:34: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
1 error generated.

Signed-off-by: frost. (frostg-012) <frost@nusantararom.org>